name: CI

on:
  push:
    branches:
      - main
      - 'v*'
  pull_request: {}
  schedule:
    - cron:  '0 3 * * *' # daily, at 3am

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.os }}

    strategy:
       matrix:
         os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ github.token }}

      - uses: actions/setup-java@v2.5.1
        with:
          java-version: '17'
          distribution: 'zulu'

      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - run: chmod +x ./gradlew
      - run: ./gradlew assemble
      - run: ./gradlew check
  update:
    name: Update Changelog and create Tag
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ github.token }}
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: create changelog and tag
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_COMMIT: ${{ github.sha }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          version=$(sh ./gradlew -q printVersion)
          git fetch --all --tags
          TAG=v$version
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "tag exists";
          else
            export GITHUB_AUTH=$GITHUB_TOKEN
            export changelog=$(npx lerna-changelog --repo $GITHUB_REPO --next-version=$version)
            echo "$changelog" | sh ./gradlew updateChangelog
            echo -e "# Changelog\n\n$changelog\n$(tail --lines=+2 CHANGELOG.md)" > CHANGELOG.md
            git add CHANGELOG.md
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git config --local user.name "$GITHUB_ACTOR"
            git commit -m "update changelog"
            git tag $TAG
            git push
            git push --tags
          fi
  upload:
    name: Upload
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'zulu'

      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: chmod +x ./gradlew
      - run: ./gradlew buildPlugin && ls ./build/distributions
      - uses: actions/upload-artifact@v3
        with:
          name: EmberExperimental.zip
          path: ./build/distributions/EmberExperimental.js-*.zip
